#!/bin/bash
# MPlayer OSX build script
# Adrian Stutz 2008

# **************************************************** #
# *** CONFIG

# GLOBAL CONFIG
buildconfig=`which mposx_buildconfig`
if [ $? -eq 0 ]; then
	
	# Load global config
	source mposx_buildconfig
	
else
	
	# Load default config
	build_root="/Users/example/dev/usr/local"
	
fi

# LOCAL CONFIG
target_system="arm64"

# **************************************************** #
# *** OPTION PARSING

usage() {
cat << EOF
Usage: source $0 [options] [arm64]

General options:
    -h, --help                  display this help

The target system is arm64 (Apple Silicon).
Headers and configure flags will be set accordingly.
EOF
}

# Parse command line
while [ -n "$1" ]; do
	case $1 in
		arm64 )								target_system=$1
											;;
		-h | --help )		 				usage
							 				exit
							 				;;
		* )					 				usage
							 				exit 1
	esac
	shift
done

# **************************************************** #
# *** SET PATHS / FLAGS

# Configure deployment target and SDK
deployment_target=11.0
sdk_path=$(xcrun --show-sdk-path)

# Make sure pkg-config doesn't interfere
export PKG_CONFIG_PATH="${build_root}/bin/pkg-config"
# Reset path to default + our own build root
export PATH="${build_root}/bin:/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
# Add scripts path
export PATH="$scripts_path:$PATH"

# Set deployment target and SDK
export MACOSX_DEPLOYMENT_TARGET=$deployment_target
export CFLAGS="-mmacosx-version-min=${deployment_target} -isystem ${sdk_path}"
export LDFLAGS="-mmacosx-version-min=${deployment_target} -isysroot ${sdk_path}"
export LDFLAGS="$LDFLAGS -Wl,-syslibroot,${sdk_path}"
export CXXFLAGS="-mmacosx-version-min=${deployment_target} -isysroot ${sdk_path}"

# Apple Silicon (arm64) platform flags
if [ $target_system = "arm64" ]; then
	export CFLAGS="$CFLAGS -arch arm64"
	export LDFLAGS="$LDFLAGS -arch arm64"
	export CXXFLAGS="$CXXFLAGS -arch arm64"
fi

# Set paths
export LDFLAGS="$LDFLAGS -L${build_root}/lib -Wl,-search_paths_first"
export CFLAGS="$CFLAGS -I${build_root}/include"
export CXXFLAGS="$CXXFLAGS -I${build_root}/include"

export BUILD_ROOT="$build_root"

echo "Headers set for target system: $target_system"
echo "Using build root: $build_root"